Fix Android build
The NDK headers nowaday has timezone in time.h, so trying to redefine it
causes the build to fail with:

proxy/store.c:34:18: error: static declaration of 'timezone' follows non-static declaration
static long int  timezone = 0;
                 ^
include/time.h:42:17: note: previous declaration is here
extern long int timezone;